### ISSUE TITLE
Personer med nok stemmer kommer opp som alternativ

### ISSUE THREAD

**Issue by ribrokken** [rankingnorway/issues#7]
Når jeg går gjennom personer som ikke har treff i ritt kommer jeg over flere som har 3 eller flere stemmer. Er det nødvendig at disse kommer opp for meg?

http://www.rittranking.no/import/match_que?id=4587

Mvh
Richard

**Comment by ribrokken** [comment]
Ett eksempel til
http://www.rittranking.no/import/match_que?id=4587

**Comment by bolav** [comment]
Listen er sortert, så når du får disse trenger du ikke ta resten for det rittet. Bare hvis du vil gå igjennom å sjekke.

**Comment by bolav** [comment]
Kanskje bedre å hoppe over de som er ferdig, hvis man ikke trykker på nytt. Og da få mulighet til å få opp de du har hoppet over på nytt.
